# Generated by Django 4.2.5 on 2024-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0030_vacantvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollnumber',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
