# Generated by Django 4.2.5 on 2024-03-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0031_rollnumber_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_subject', models.CharField(default='', max_length=100)),
                ('sub_section', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='studease.subsection')),
            ],
        ),
    ]
