# Generated by Django 4.2.5 on 2024-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0034_delete_userattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='userattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rollnumber', models.IntegerField(default=0, max_length=100)),
                ('user_subject', models.CharField(default='', max_length=100)),
                ('user_actions', models.CharField(default='noclass', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
