# Generated by Django 4.2.5 on 2024-03-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studease', '0035_userattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userattendance',
        ),
    ]
